### ISSUE TITLE
Page d'aide jimconvert() terminée

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#1]
La rédaction de la page d'aide de la fonction jimconvert() en français est terminée. 
Pouvez vous m'indiquer les points à changer avant la traduction en anglais ? 

[Page d'aide jimconvert()](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimconvert.xml)

**Comment by sgougeon** [comment]
La version initiale de la page jimconvert() en fr_FR est commentée dans le fichier joint.
[jimconvert_help_170420_REMS.pdf](https://github.com/jimlab/jimlab/files/946150/jimconvert_help_170420_REMS.pdf)

**Comment by Camtarrr** [comment]
La version corrigée de la page d'aide de jimconvert() est disponible sur le git. 
[Page d'aide actualisée](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimconvert.xml)
Il reste seulement le problème de l'image à régler mais il fait l'objet d'un autre ticket. Il n'empêche pas la traduction de la page.

**Comment by sgougeon** [comment]
Merci. Les éléments nouvellement décrits m'ont invité à de nouvelles remarques consignées ci-joint.
Après cela, vous pourrez entreprendre la traduction en anglais sans resoumettre la version française.
[jimconvert_help_20170510_REMS.pdf](https://github.com/jimlab/jimlab/files/990753/jimconvert_help_20170510_REMS.pdf)

**Comment by Camtarrr** [comment]
L'argument `colormap` est obligatoire dans le cas ou l'image est indexée, sinon nous ne pouvons pas savoir si il s'agit d'une matrice d'index ou d'une matrice d'intensités.

**Comment by sgougeon** [comment]
OK. Dans ce cas, serait-il possible d'autoriser la fourniture d'un identifiant de figure tel que gcf(), en alternative à une color_map, et le cas échéant, de lire -- disons -- colormap = gcf().color_map en interne ?
Sinon, à minima, il faudrait ajouter un exemple avec colormap. Exemple : 
```
clf
f = gcf();
nc = size(f.color_map,1);
M = grand(100,130,"uin",1,nc);
Mgray = jimconvert(M, "gray", f.color_map);
subplot(1,2,1), jimdisp(M)
subplot(1,2,2), jimdisp(Mgray)
```
Pb: cet exemple provoque une erreur (d'où l'utilité d'un test unitaire)
```
--> Mgray = jimconvert(M, "gray", f.color_map);
à la ligne    19 de la fonction jimconvert ( H:\PROJETS\4A\jimlab\jimlab-master\macros\jimconvert.sci ligne 27 )
jimconvert: Argument #3: hypermatrix with 3 components expected.
```

**Comment by sgougeon** [comment]
> Dans ce cas, serait-il possible d'autoriser la fourniture d'un identifiant de figure tel que gcf(), 

Abandonner cette idée. Il y a actuellement d'autres priorités, en particulier corriger l'erreur relevée avec la syntaxe déjà disponible.

**Comment by sgougeon** [comment]
>L'argument colormap est obligatoire dans le cas ou l'image est indexée, sinon nous ne pouvons pas
>savoir si il s'agit d'une matrice d'index ou d'une matrice d'intensités.

Toutes les matrices d'intensité ne sont-elles pas attendues en entiers encodés ? En fait, l'aide est actuellement ambigüe, car elle ne fait pas explicitement référence aux types uint# ou int#.
Par exemple : 
>une matrice d'entiers sur 32 bits (signés ou non signés) 

S'agit-il de
>une matrice d'entiers sur 32 bits (int32 ou uint32)

ou peut-on fournir des entiers encodés _en décimaux_ mais <= 2^32 - 1 ?

**Comment by Camtarrr** [comment]
La majorité des problèmes relevés vient de la fonction jimstandard() dont les tests unitaires n'ont pas encore été écrits.

**Comment by Camtarrr** [comment]
```
clf
f = gcf();
nc = size(f.color_map,1);
M = grand(100,130,"uin",1,nc);
Mgray = jimconvert(M, "gray", f.color_map);
subplot(1,2,1), jimdisp(M)
subplot(1,2,2), jimdisp(Mgray)
```
Les syntaxes étaient mal rédigées, je les ai modifiées. Le deuxième argument attendu est la couleur de transparence, la syntaxe doit donc être 

`Mgray = jimconvert(M, "gray", , f.color_map);`

Avec cette syntaxe, il n'y a plus d'erreur.

**Comment by Camtarrr** [comment]
> Dans ce cas, serait-il possible d'autoriser la fourniture d'un identifiant de figure tel que gcf(),

J'essaierai d'implémenter cela dans la fonction jimstandard() dès que les pages d'aide en français et en anglais de jimconvert() sont finalisées (d'ici ce soir normalement)

**Comment by Camtarrr** [comment]
L'argument colormap peut désormais être un identifiant de figure.
