### ISSUE TITLE
Page d'aide en français jimage_properties

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#10]
La première version de la page d'aide concernant l'objet jimage est terminée. 
Serait-il possible d'avoir des retours avant la traduction? 

[Page d'aide jimage_properties](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimage_properties.xml)

**Comment by sgougeon** [comment]
La version courante en français de jimage_properties accompagnée de mes commentaires est jointe.
À mon sens (voir les commentaires), le code doit être retouché en particulier
* pour renommer .format en .mime
* pour enlever le . initial dans les valeurs possibles de .mime : ".png" => "png"
Par ailleurs, les fonctions doivent être robustes concernant la casse des valeurs : "png" comme "PNG" comme "Png" etc doivent être acceptés par les fonctions du module. Si c'est déjà le cas => ajouter cette information à la description du champ. Sinon : soit l'implémenter (si ce n'est pas long), soit le mettre dans la liste TODO pour développement ultérieur.
[jimage_properties_help_20170416_REMS.pdf](https://github.com/jimlab/jimlab/files/929158/jimage_properties_help_20170416_REMS.pdf)
