### ISSUE TITLE
GitHub : liens framaboard bimestriels : contenus supprimés

### ISSUE THREAD

**Issue by sgougeon** [jimlab/jimlab#11]
Dans l'onglet jimlab => Projects, les liens framaboard bimestriels sont caduques : 
* étude des différents formats d'images supportés par java : https://bimestriel.framapad.org/p/Formats_images_java
* compte-rendus de réunions hebdomadaires : https://bimestriel.framapad.org/p/Compte-rendus_Jimlab 

En restaurer le contenu ou les supprimer.
Je laisse le pilote de projet attribuer ce travail à un membre.

**Comment by Camtarrr** [comment]
Les compte-rendus de réunions hebdomadaires sont toujours disponibles. 
Pour le premier lien, toutes les informations avaient été reprises dans le rapport de soutenance intermédiaire. Nous allons le supprimer.
