### ISSUE TITLE
jimconvert() : multiplication d'une matrice par une hypermatrice

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#15]
Bonjour, 
Pour la fonction jimconvert(), j'aimerais obtenir une hypermatrice avec des 0 lorsque l'image est opaque et la couleur de transparence lorsque l'image n'est pas opaque. J'ai essayé avec le code suivant (et d'autres) :
```
transparency = jimage(:,:,4) == 0;
transparencyMat = uint8(transparency) .* transparencyColor;
```
transparencyColor est une hypermatrice avec un élément sur chaque couche et transparency une matrice. 
J'obtiens le message d'erreur suivant : 
```
                                                          !--error 144 
Opération non définie pour les opérandes données.
Vérifier ou définir la fonction %i_x_hm pour la surcharge.
```

Je suppose qu'il existe  une manière de faire cette opération en Scilab mais je ne la trouve pas. Serait-il possible d'avoir de l'aide ?

**Comment by Camtarrr** [comment]
Finalement le code suivant fonctionne mais il est un peut lourd. 
```
               transparencyMat(:,:,1) = uint8(transparency) .* transparencyColor(:,:,1);
               transparencyMat(:,:,2) = uint8(transparency) .* transparencyColor(:,:,2);
               transparencyMat(:,:,3) = uint8(transparency) .* transparencyColor(:,:,3);
```
S'il existe une meilleure solution, dites moi. Sinon vous pouvez fermer le ticket.

**Comment by sgougeon** [comment]
Vous pouvez utiliser directement le produit de kronecker. Exemples :
```
clc
image = rand(3,5)
transparency = image < 0.3
transparencyColor = cat(3, 72,16,153)
transparencyMat = uint8(transparency) .*. transparencyColor
```
Résultat :
```
--> image = rand(3,5)
 image  = 
   0.5617307   0.7901072   0.4256872   0.1000746   0.0366117
   0.468176    0.9808542   0.2461561   0.4678218   0.5175369
   0.7794547   0.8187066   0.9229532   0.3950498   0.8325452

--> transparency = image < 0.3
 transparency  = 
  F F F T T
  F F T F F
  F F F F F

--> transparencyColor = cat(3, 72,16,153)
 transparencyColor  = 
(:,:,1)
   72.
(:,:,2)
   16.
(:,:,3)
   153.

--> transparencyMat = uint8(transparency) .*. transparencyColor
 transparencyMat  = 
(:,:,1)
   0.   0.   0.    72.   72.
   0.   0.   72.   0.    0. 
   0.   0.   0.    0.    0. 
(:,:,2)
   0.   0.   0.    16.   16.
   0.   0.   16.   0.    0. 
   0.   0.   0.    0.    0. 
(:,:,3)
   0.   0.   0.     153.   153.
   0.   0.   153.   0.     0.  
   0.   0.   0.     0.     0.  
```

**Comment by Camtarrr** [comment]
J'ai essayé avec le produit de kronecker. J'obtiens l'erreur suivante sur la console. 
La seconde syntaxe `kron(A, B)` donne le même résultat. La documentation de la fonction dit "Cependant le produit de Kronecker n'est pas défini entre une matrice creuse et une hypermatrice.". Le fait que ma matrice `transparency` contienne beaucoup de 0 est peut être à l'origine de l'erreur.

```
-->transparency = jimage(:,:,4) == 0;
 
-->size(transparency)
 ans  =
 
    826.    1169.  
 
-->transparencyColor
 transparencyColor  =
 
(:,:,1)
 
  255  
(:,:,2)
 
  255  
(:,:,3)
 
  255  
 
-->transparencyMat = uint8(transparency) .*. transparencyColor;
                                            !--error 144 
Opération non définie pour les opérandes données.
Vérifier ou définir la fonction %i_k_hm pour la surcharge.
```

**Comment by sgougeon** [comment]
OK : ça fonctionne sous 6.0, mais pas sous 5.5.
Du reste, sous 6.0, le résultat est de type décimal au lieu d'être du type uint8. C'est une anomalie. Je verrai ça à part pour SCilab central.
Une syntaxe valable en 5 comme en 6 est 
`transparencyMat = uint8(transparency*1  .*. transparencyColor)`
Celle-ci a en outre le mérite d'avoir un résultat en uint8

**Comment by Camtarrr** [comment]
J'obtiens l'image suivante en sortie lorsque j'utilise le produit de Kronecker

![logoensimkron](https://cloud.githubusercontent.com/assets/24584359/25491994/f137b2f8-2b71-11e7-80e3-052a0e186591.png)

Je laisse donc la syntaxe de départ qui pourra être modifiée en fonction du temps restant à la fin du projet. 
Merci !

**Comment by sgougeon** [comment]
> J'obtiens l'image suivante en sortie lorsque j'utilise le produit de Kronecker

Pourriez-vous SVP m'indiquer les lignes de codes appelées qui produisent cet affichage ?
Merci

**Comment by Camtarrr** [comment]
```
path = jimlabPath() + '\tests\images\logoEnsim.png';
jim = jimread(path)
jimage = jim.image;
transparencyColor = cat(3, uint8(255), uint8(255), uint8(255));
transparency = jimage(:,:,4) == 0;
transparencyMat = uint8(transparency*1 .*. transparencyColor);
convertedMat(:,:,1) = jimage(:,:,1) .* uint8(~transparency);
convertedMat(:,:,2) = jimage(:,:,2) .* uint8(~transparency);
convertedMat(:,:,3) = jimage(:,:,3) .* uint8(~transparency);
convertedJimage = transparencyMat + convertedMat;
jimdisp(convertedMat)
```
Sur Scilab 6.0.0, l'image convertie est la bonne. Sur Scilab 5.5.2, la matrice transparencyMat est fausse ( plusieurs coefficients différents sur chaque couche) et l'image de sorte est celle postée plus haut.
