### ISSUE TITLE
tests unitaires jimconvert()

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#17]
J'ai un soucis avec le test unitaire concernant le deuxième argument de jimconvert(). Lorsque je lance le code suivant : 
```
//Wrong second argument
msg = "%s: Argument #%d: rgb or gray expected.\n";
jim = jim.image;
assert_checkerror("rgba = jimconvert(jim , ""rgba"")", msg, [], "jimconvert", 2)
```
J'obtiens cette erreur : 
`assert_checkerror: Assertion failed: expected error message = "jimconvert: Argument #2: rgb or gray expected." while computed error message = "Nombre erroné d'arguments d'entrée.".`

Quand je lance la ligne de code testée dans le assert_checkerror, j'obtiens bien l'erreur voulue. 
```
-->rgba = jimconvert(jim, "rgba")
 !--error 10000 
jimconvert: Argument #2: rgb or gray expected.
at line     100 of function jimconvert called by :  
rgba = jimconvert(jim, "rgba")
```

**Comment by sgougeon** [comment]
Je suis très étonné que les appels de assert_checkerror() tels que dans 
```
msg = "%s: Argument #%d: rgb or gray expected.\n";
jim = jim.image;
assert_checkerror("rgba = jimconvert(jim , ""rgba"")", msg, [], "jimconvert", 2)
```
ne donnent pas systématiquement une erreur. Cette syntaxe semble parfois possible, mais l'aide à son propos me semble tellement confuse que je ne suis pas certain que cela fasse ce que cela devrait.
Une manière beaucoup plus directe consiste à générer le vrai message d'erreur et à le passer à assert_checkerror() : 
```
msg = "%s: Argument #%d: rgb or gray expected.\n";
msg = msprintf(msg, "jimconvert", 2);
jim = jim.image;
assert_checkerror("rgba = jimconvert(jim , ""rgba"")", msg);
```
Lorsque l'on fait cela, le test ne passe toujours pas, mais pour une autre raison qui est un bug identifiable dans jimstandard():
```
   failed: Slave Scilab exited with error code 1
   
   ----- TMPDIR\jimconvert.res: 10 last lines: -----
    RGBA encoding
    RGBA encoding
   --> //Wrong second argument
   --> msg = "%s: Argument #%d: rgb or gray expected.\n";
   --> msg = msprintf(msg, "jimconvert", 2);
   --> assert_checkerror("rgba = jimconvert(jim.image , ""rgba"")", msg);
   WARNING: Bad argument type for argb, rgba standard will be used.
   at line   126 of function assert_checkerror ( H:\DISTRI_DOC_ETU\APPLI_RESEAU\Scilab\Scilab-6.0.0\modules\development_tools\macros\assert\assert_checkerror.sci line 138 )
   at line    83 of executed file TMPDIR\jimconvert.tst
   assert_checkerror: Assertion failed: expected error message = "jimconvert: Argument #2: rgb or gray expected." while computed error message = "Undefined variable: jimstandard_ind".
```
 "Undefined variable: jimstandard_ind" :
En effet, dans jimstandard.sci, cet identificateur n'est jamais défini.
À corriger
