### ISSUE TITLE
Relecture page d'aide jimread() en anglais

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#18]
J'ai fini de traduire ma page d'aide. Est ce que tu pourrais jeter un coup d’œil pour voir si il n'y a pas de faute d'anglais ? 

[Page d'aide](https://github.com/jimlab/jimlab/blob/master/help/en_US/jimread.xml )

**Comment by JimSenee** [comment]
**Section Arguments :**

Sous l’item imagePath : il manque un bout de phrase si on se réfère à la version en français.
Il faudrait écrire ‘The different MIME types handled are png, bmp…’.
Petite faute de frappe : Alpha channel (toujours à la même ligne 35) s’écrit de la même façon qu’en français.

**Section Description :**

Rien à redire à part quelques fautes de frappes :
integers (ligne 60)
or (ligne 65)

Sinon tout va bien !
