### ISSUE TITLE
Utilisation de la balise <scilab:image>

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#19]
Lorsque j'utilise des fonctions du module jimlab dans la balise <scilab:image>, elles ne sont pas reconnues et cela bloque le chargement du module. J'obtenais au début l'erreur suivante : 
`Variable non définie : jimlabPath`
J'ai donc remplacé jimlabPath("/") par get_absolute_file_path("builder.sce") dans la balise <scilab:image> mais le même problème intervient avec l'appel de la fonction jimread() :
`Variable non définie : jimread
`
Si je ne peux pas appeler les fonctions du module dans cette balise, je ne comprends pas comment illustrer mes pages d'aide. Serait-il possible d'avoir de l'aide ?

**Comment by sgougeon** [comment]
Merci de me bien vouloir poster soit un lien vers un fichier d'aide modifié qui vous pose problème, soit directement ledit fichier en question. Je n'en ai pas trouvé dans ~/help sur GitHub

**Comment by Camtarrr** [comment]
[page d'aide de la fonctcion jimconvert()](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimconvert.xml)

**Comment by sgougeon** [comment]
Il faut charger le module (jimlablib) avant de le recompiler.
Par ailleurs, j'observe sur Git que en_US/jimconvert.xml n'est pas synchronisé avec fr_FR, notamment n'inclut pas les balises <scilab:image>. Ca peut poser problème.
Après avoir fait cela, jimlabPath() ne pose plus de problème, mais une erreur due à jimconvert() apparait.
L'examen rapide du code de jimconvert() met en évidence des problèmes potentiels d'initialisation : 
Par exemple, dans le cas 
`elseif (type(jimage) == 4)`
name et ext ne sont pas initialisés.
Par ailleurs, comme déjà évoqué lors d'une de nos réunions, isdef() doit toujours être utilisée avec l'option "l", sans quoi vous rendez la jimconvert() sensible à des objets externes hors liste d'arguments.
Je vous laisse traiter ces différents problèmes. Merci de me tenir informé.

**Comment by sgougeon** [comment]
J'ajoute que dans jimconvert.sci, de très nombreux ".." ne sont pas justifiés et diminuent la lisibilité du code.

**Comment by Camtarrr** [comment]
J'ai mis à jour la fonction jimconvert() en prenant compte de vos remarques. Elle n'est pas encore sur le git car j'ai remarqué qu'il y avait des modifications à effectuer concernant la couleur de transparence. Je vous informerais dès qu'elle sera à jour sur le git. 
Il reste quand même un problème que je n'arrive pas à résoudre. Lorsque j'affiche la page d'aide de jimconvert, il manque la dernière image : 
![affichagepagedaide](https://cloud.githubusercontent.com/assets/24584359/25812752/8e76d582-3417-11e7-9ac6-96a5758798b6.png)
alors que quand j’exécute le code inclut dans la balise directement dans la console, la quatrième image s'affiche comme voulu : 
![affichageconsole](https://cloud.githubusercontent.com/assets/24584359/25812809/c0749286-3417-11e7-9525-2336d2bab5b5.png)

**Comment by Camtarrr** [comment]
La nouvelle version de jimconvert() est sur le git

**Comment by sgougeon** [comment]
Le subplot manquant lors de l'exportation via le compilateur de pages est un bug de Scilab.
J'en prends note et le déclarerai sur bugzilla plus tard.
Il est assez sérieux, car il bloque l'exportation de tous les éléments graphiques suivants. En effet, si dans l'exemple de jimconvert() on commence par la partie subplot(2,2,4), puis les 3 autres, tout devient blanc.
Pourtant, xs2png() -- dont on pourrait penser qu'elle est utilisée par le compilateur -- fonctionne correctement.

Pour ce qui concerne la mise en oeuvre des balises `<scilab:image>`, votre question initiale est résolue.
Je ferme donc ce ticket.
Comme indiqué dans la revue de la page de jimconvert(), nous générerons l'image correcte avec xs2png() à la main et l'insérerons dans le .jar pour publication. C'est noté dans le tableau d'avancement.
