### ISSUE TITLE
Page d'aide jimhistEqual() terminée

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#2]
La rédaction de la page d'aide de la fonction jimhistEqual() en français est terminée.
Pouvez vous m'indiquer les points à changer avant la traduction en anglais ?

[Page d'aide jimhistEqual()](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimhistEqual.xml)

**Comment by sgougeon** [comment]
Cette version accompagnée de mes commentaires est jointe.
[jimhistEqual_help_20170416_REM.pdf](https://github.com/jimlab/jimlab/files/928582/jimhistEqual_help_20170416_REM.pdf)
