### ISSUE TITLE
Relecture page d'aide en anglais : jimdisp()

### ISSUE THREAD

**Issue by JimSenee** [jimlab/jimlab#21]
La page d'aide en anglais pour la fonction d'affichage jimdisp() est finalisée.
Peux-tu la relire ?
Merci !

[Page d'aide jimdisp() (anglais)](https://github.com/jimlab/jimlab/blob/master/help/en_US/jimdisp.xml)

**Comment by Camtarrr** [comment]
"A matrix or hypermatrix", j'aurais mis "a hypermatrix". 
L'argument "data" devrait être "image" pour correspondre avec les syntaxes.
Le champs format devient type MIME. 
Dans le premier exemple, il y a un séparateur en trop entre jimlabPath() et les reste de chemin. 
Dans l'historique : Initial publication of Jimlab module.
C'est tout !
