### ISSUE TITLE
Problème de compilation page d'aide jimwrite 

### ISSUE THREAD

**Issue by nicojim** [jimlab/jimlab#22]
La page d'aide de jimwrite à été modifier mais elle refuse actuellement de ce compiler. Pourtant, ni le vérificateur de note pad ++, ni la fonctions xmltohtml ne renvois d'erreur.
Le code de la page d'aide ne semble pas contenir d'erreur mais la builder ne crée pas le fichier html associer à jimwrite.xml.

Compilation avec xmltohtml : 
 
--> directory = '/home/nicolas/Documents/Scilab/jimlab-master/help/fr_FR/'
 directory  = 

 /home/nicolas/Documents/Scilab/jimlab-master/help/fr_FR/

--> my_french_help_title  = 'jimwrite.xml'
 my_french_help_title  = 

 jimwrite.xml

--> mydir = xmltohtml(directory ,my_french_help_title,'fr_FR')

Génération du document maître :
	/home/nicolas/Documents/Scilab/jimlab-master/help/fr_FR/

Génération du fichier d'aide [html] in /home/nicolas/Documents/Scilab/jimlab-master/help/fr_FR/.
 mydir  = 

 /home/nicolas/Documents/Scilab/jimlab-master/html/fr_FR/index.html

**Comment by sgougeon** [comment]
Avant que je regarde : le compilateur des pages affiche la plupart des erreurs de compilation dans la "consolebox" => ouvrir la consolebox:
`consolebox on`  // dans la console
Puis compiler. Lorsqu'une erreur de compilation a lieu, il est assez fréquent qu'un des flux entrant (lecture du xml) ou sortant (écriture du HTML) ne soit pas fermé proprement, ce qui peut laisser le fichier concerné verrouillé, et provoque une erreur si l'on tente de recompiler. Si vous soupçonnez ce type de problème, la seule solution est de fermer la session Scilab verrouillant le fichier, et d'en ouvrir une nouvelle.

**Comment by nicojim** [comment]
Oui merci le problème est résolue
