### ISSUE TITLE
Page d'aide jiminvert

### ISSUE THREAD

**Issue by nicojim** [jimlab/jimlab#23]
La page d'aide de jiminvert est terminer et est prête à être traduite. J'attends vos remarques.

**Comment by sgougeon** [comment]
SVP vérifier a minima avant de poster que les exemples fonctionnent correctement.
Mes remarques sont jointes au PDF ci-dessous.
[jiminvert_help_170511_REMS.pdf](https://github.com/jimlab/jimlab/files/1007112/jiminvert_help_170511_REMS.pdf)

**Comment by JimSenee** [comment]
La page d'aide a été modifiée selon vos remarques.
