### ISSUE TITLE
Syntaxes pour la fonction interne jimstandard()

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#24]
##  Proposition de syntaxes

```
image = jimstandard(imageMat);
image = jimstandard(imageMat, colormap);
image = jimstandard(imageMat, argb?);
image = jimstandard(imageMat, colorsBits);
```
## Définition des arguments 

imageMat : 
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 4 couches dont les couleurs sont encodées en RGBA
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 4 couches dont les couleurs sont encodées en ARGB
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 3 couches dont les couleurs sont encodées en RGB
- Une matrice d'entiers 8 bits (uint8 ou int8) dont les couleurs sont encodées en niveaux de gris ou en "rgb332" (dans ce cas là il faut renseigner l'argument colorsBits)
- Une matrice de numéros de couleurs telles que répertoriées dans la table de couleur définie par l'argument `colormap`
- Un matrice d'entiers 16 bits (uint16 ou int16) dont l'encodage des couleurs est défini par l'argument colorsBits (par défaut on prendra "rgba444", qui est l'encodage par défaut de `Matplot()`)
- Une matrice d'entiers 32 bits (uint32 ou int32) dont les couleurs sont encodées en RGBA
- Une matrice d'entiers 32 bits (uint32 ou int32) dont les couleurs sont encodées en ARGB
- Une matrice de booléens (%f = noir, %t = blanc)
- Une hypermatrice de doubles normalisés entre 0 et 1 à 4 couches dont les couleurs sont encodées en RGBA
- Une hypermatrice de doubles normalisés entre 0 et 1 à 4 couches dont les couleurs sont encodées en ARGB
- Une hypermatrice de doubles normalisés entre 0 et 1 à 3 couches dont les couleurs sont encodées en RGB
- Une matrice de doubles normalisés entre 0 et 1 dont les couleurs sont encodées en niveaux de gris
- Une matrice de doubles représentant des entiers 8 bits, 16 bits ou 32 bits (signés ou non signés)

colormap : 
- Une matrice de dimensions M x 3. M est le nombre de couleurs de la colormap. Pour chaque ligne, les trois coefficients définissent l'intensité du rouge, du vert et du bleu normalisée entre 0 et 1
- Un identifiant de figure

argb? : 
Un booléen : `%t` si l'image est encodée en ARGB, `%f` sinon. S'il n'est pas renseigné, sa valeur est `%f` (valeur par défaut de `Matplot()`) 

colorsBits : 
Une chaîne de caractère donnant le type d'encodage pour une matrice en entrée codée en entiers 16 bits ou en entiers 8 bits : 
- "4444" (seulement pour 16 bits)
- "444" (seulement pour 16 bits)
- "5551" (seulement pour 16 bits)
- "555" (seulement pour 16 bits)
- "332" (seulement pour 8 bits)

image : 
- une hypermatrice d'uint8 à 4 couches dont les couleurs sont encodées en RGBA
- une hypermatrice d'uint8 à 3 couches dont les couleurs sont encodées en RGB
- une matrice d'uint8 dont les couleurs sont encodées en niveaux de gris

## Commentaire

Est ce que vous validez ces syntaxes pour la fonction `jimstandard()` sachant qu'elle resterait interne au module ? 
Si non, j'attends vos remarques avant de modifier le code de cette fonction.

**Comment by sgougeon** [comment]
>Est ce que vous validez ces syntaxes pour la fonction `jimstandard() ?`

Oui
 
>Matplot() ne prend pas en charge le cas "4444" où le canal alpha est encodé sur les 4 premiers bits. `gce().image_type` peut prendre la valeur "argb" ou la valeur "rgba444" mais pas les deux en même temps. En revanche cela ne nous empêche pas de gérer ce type de matrice d'entrée si il vous parait pertinent. 

C'était bien la question (suite ci-dessous).
>Dans ce cas, il faudrait séparer l'argument `argb?` de `colorsBits` et `colormap`. Cela ne risque pas d'alourdir les syntaxes de jimstandard() ? 

Il faudrait surtout pouvoir _cumuler_ `argb?` et `colorsBits`. C'est faisable sans difficulté (car la désambiguation est simple), mais pas du tout prioritaire, et voire même peut-être finalement inutile. Je préfère en rester là, sans cumul possible pour le moment. Si des utilisateurs tombent sur un format "4444" en "argb" au lieu de "rgba" et que le "argb" se révèle fréquent, nous implémenterons ce qu'il faut le moment venu.

Concernant la description des arguments : modifications proposées : 
_imageMat_ : 
- **en couleurs**
  - hypermatrice RGB ou RGBA ou ARGB (avec argb?=%t) d'entiers int8 ou uint8, ou de décimaux sur [0, 1].
  - matrice 
    - d'entiers uint8 ou int8 sous découpage binaire "rgb332" (colorsBits="332"), ou décimaux équivalents sur [0, 255].
    - d'entiers uint16 ou int16 sous découpage binaire "rgba4444" (ou autre fixé par colorsBits), ou décimaux équivalents sur [0, 2^16-1]
    - d'entiers uint32 ou int32 sous découpage binaire "rgba8888" (ou "argb8888" si argb?=%t), ou décimaux équivalents sur [0, 2^32-1]
    - de n° entiers (décimaux, int# ou uint#) de couleurs référencées dans colormap.
- **en niveaux de gris** :  matrice d'entiers uint8 ou int8, ou de décimaux sur [0, 1], ou de booléens. Blanc = 255 | 127 | 1.0 | %t.

**Remarque** : ici comme partout, SVP éviter d'utiliser le terme `double`. Utiliser plutôt  `nombre décimal`, ou `décimaux` (`decimal number` ou `decimal numbers`)

colormap : 
- Matrice de taille M x 3 de décimaux sur [0, 1]. Ligne n° i = intensités `[R V B]` de la couleur n° i.
- Un identifiant de figure, dont l'attribut `.color_map` est utilisé

argb? : 
Un booléen : `%t` si l'image est encodée en ARGB ou argb####, `%f` sinon. Par défaut, il est `%f`.

colorsBits : 
Une chaîne de caractère indiquant le découpage binaire RVB ou RVBA des couleurs d'une matrice d'entrée spécifiées
 - en entiers 8 bits : "332"
 - en entiers 16 bits : "4444", "5551", "555" (dernier bit ignoré), ou "444" (4 derniers bits ignorés).

image : 
- une hypermatrice d'uint8 à 4 couches dont les couleurs sont encodées en RGBA
- une hypermatrice d'uint8 à 3 couches dont les couleurs sont encodées en RGB
- une matrice d'uint8 de niveaux de gris
