### ISSUE TITLE
Syntaxes de la fonction jimconvert()

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#25]
## Proposition de syntaxes

convertedImage = jimconvert(image, encoding);
convertedImage = jimconvert(image, encoding, colormap);
convertedImage = jimconvert(image, encoding, argb?);
convertedImage = jimconvert(image, encoding, colorsBits);
convertedImage = jimconvert(image, encoding, argb?, transparencyColor);
convertedImage = jimconvert(image, encoding, colorsBits, transparencyColor);
convertedImage = jimconvert(image, encoding, , transparencyColor);

## Définition des arguments

image : 
- Un objet jimage
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 4 couches dont les couleurs sont encodées en RGBA
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 4 couches dont les couleurs sont encodées en ARGB
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 3 couches dont les couleurs sont encodées en RGB
- Une matrice d'entiers 8 bits (uint8 ou int8) dont les couleurs sont encodées en "rgb332"
- Une matrice de numéros de couleurs telles que répertoriées dans la table de couleur définie par l'argument `colormap`
- Un matrice d'entiers 16 bits (uint16 ou int16) dont l'encodage des couleurs est défini par l'argument `colorsBits` (par défaut on prendra "rgba444", qui est l'encodage par défaut de `Matplot()`)
- Une matrice d'entiers 32 bits (uint32 ou int32) dont les couleurs sont encodées en RGBA
- Une matrice d'entiers 32 bits (uint32 ou int32) dont les couleurs sont encodées en ARGB
- Une matrice de booléens (`%f` = noir, `%t` = blanc)
- Une hypermatrice de doubles normalisés entre 0 et 1 à 4 couches dont les couleurs sont encodées en RGBA
- Une hypermatrice de doubles normalisés entre 0 et 1 à 4 couches dont les couleurs sont encodées en ARGB
- Une hypermatrice de doubles normalisés entre 0 et 1 à 3 couches dont les couleurs sont encodées en RGB
- Une matrice de doubles représentant des entiers 8 bits, 16 bits ou 32 bits (signés ou non signés)

encoding : 
Mot `"gray"` ou `"rgb"` : encodage souhaité en sortie

colormap :
- Une matrice de dimensions M x 3. M est le nombre de couleurs de la `colormap`. Pour chaque ligne, les trois coefficients définissent l'intensité du rouge, du vert et du bleu normalisée entre 0 et 1
- Un identifiant de figure

argb? :
Un booléen : `%t` si l'image est encodée en ARGB, `%f` sinon. S'il n'est pas renseigné, sa valeur est `%f` (valeur par défaut de `Matplot()`)

colorsBits :
Une chaîne de caractère donnant le type d'encodage pour une matrice en entrée codée en entiers 16 bits ou en entiers 8 bits :
- "4444" (seulement pour 16 bits)
- "444" (seulement pour 16 bits)
- "5551" (seulement pour 16 bits)
- "555" (seulement pour 16 bits)
- "332" (seulement pour 8 bits)

transparencyColor : 
- Un vecteur ou une hypermatrice à trois composantes dans l'intervalle [0;255] si l'argument `encoding` vaut `"rgb"`
- Un scalaire dans l'intervalle [0;255] si l'argument `encoding` vaut `"gray"`
Il correspond à la nuance de couleur affectée à tous les pixels ayant leur transparence au maximum. Par défaut, la nuance la plus claire est utilisée. Cet argument n'est utilisé que lorsque l'image d'entrée est encodée en RGBA ou en ARGB.

convertedImage : 
- un objet de type `jimage` dont les champs `.image` et `.transparencyColor` ont l'encodage correspondant à l'argument `encoding`
- une matrice de niveaux de gris encodée en uint8
- une hypermatrice à 3 couches encodées en uint8

## Commentaire

Validez vous ces syntaxes pour la fonction `jimconvert()` ? La fonction serait alors modifiée pour que `transparencyColor` corresponde effectivement à la couleur **affectée** aux pixels transparents même lorsque l'image est convertie en niveaux de gris. 
Si non, j'attends vos commentaires.

**Comment by sgougeon** [comment]
>Validez vous ces syntaxes pour la fonction `jimconvert()` ? La fonction serait alors modifiée pour que `transparencyColor` corresponde effectivement à la couleur **affectée** aux pixels transparents même lorsque l'image est convertie en niveaux de gris. 
Si non, j'attends vos commentaires. 

Comme pour jimhistEqual() et les autres, l'image d'entrée doit être standard, ou ici une jimage. Donc les options arg?, colorsBits et colormap disparaissent. Si l'image d'entrée est une matrice ou une hypermatrice, jimstandard() lui est appliquée en interne. Au pire elle ne fait rien. Au mieux elle standardise avec les options par défaut. Si l'utilisateur fournit une image à interpréter autrement, il applique jimstandard() **avant** d'alimenter jimconvert(), avec les options qui conviennent.
Seule reste donc ici l'option `transparencyColor`.

N'hésitez pas à me rebasculer le ticket si vous souhaitez poursuivre la discussion. Sinon je vous laisse conclure ce point et clore le ticket.
