### ISSUE TITLE
Syntaxes de la fonction jimhistEqual()

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#26]
## Proposition de syntaxes 

equalizedImage = jimhistEqual(image);
equalizedImage = jimhistEqual(image, colormap);
equalizedImage = jimhistEqual(image, argb?);
equalizedImage = jimhistEqual(image, colorsBits);
equalizedImage = jimhistEqual(image, argb?, transparencyColor);
equalizedImage = jimhistEqual(image, colorsBits, transparencyColor);

## Description des arguments 

image :
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 4 couches dont les couleurs sont encodées en RGBA
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 4 couches dont les couleurs sont encodées en ARGB
- Une hypermatrice d'entiers 8 bits (uint8 ou int8) à 3 couches dont les couleurs sont encodées en RGB
- Une matrice d'entiers 8 bits (uint8 ou int8) dont les couleurs sont encodées en niveaux de gris ou en "rgb332" (dans ce cas là il faut renseigner l'argument` colorsBits`)
- Une matrice de numéros de couleurs telles que répertoriées dans la table de couleur définie par l'argument `colormap`
- Un matrice d'entiers 16 bits (uint16 ou int16) dont l'encodage des couleurs est défini par l'argument `colorsBits` (par défaut on prendra "rgba444", qui est l'encodage par défaut de `Matplot()`)
- Une matrice d'entiers 32 bits (uint32 ou int32) dont les couleurs sont encodées en RGBA
- Une matrice d'entiers 32 bits (uint32 ou int32) dont les couleurs sont encodées en ARGB
- Une hypermatrice de doubles normalisés entre 0 et 1 à 4 couches dont les couleurs sont encodées en RGBA
- Une hypermatrice de doubles normalisés entre 0 et 1 à 4 couches dont les couleurs sont encodées en ARGB
- Une hypermatrice de doubles normalisés entre 0 et 1 à 3 couches dont les couleurs sont encodées en RGB
- Une matrice de doubles normalisés entre 0 et 1 dont les couleurs sont encodées en niveaux de gris
- Une matrice de doubles représentant des entiers 8 bits, 16 bits ou 32 bits (signés ou non signés)

colormap :
- Une matrice de dimensions M x 3. M est le nombre de couleurs de la `colormap`. Pour chaque ligne, les trois coefficients définissent l'intensité du rouge, du vert et du bleu normalisée entre 0 et 1
- Un identifiant de figure

argb? :
Un booléen : `%t `si l'image est encodée en ARGB, `%f` sinon. S'il n'est pas renseigné, sa valeur est `%f` (valeur par défaut de `Matplot()`)

colorsBits :
Une chaîne de caractère donnant le type d'encodage pour une matrice en entrée codée en entiers 16 bits ou en entiers 8 bits :
- "4444" (seulement pour 16 bits)
- "444" (seulement pour 16 bits)
- "5551" (seulement pour 16 bits)
- "555" (seulement pour 16 bits)
- "332" (seulement pour 8 bits)

transparencyColor :
- Un vecteur ou une hypermatrice à trois composantes dans l'intervalle [0;255] si l'argument encoding vaut "rgb"
- Un scalaire dans l'intervalle [0;255] si l'argument encoding vaut "gray"

Pour une image encodée en RGBA ou en ARGB, il correspond à la nuance de couleur affectée à tous les pixels ayant leur transparence au maximum lors de la conversion en niveaux de gris. Par défaut, la nuance la plus claire est utilisée. Pour une image encodée en RGB ou en niveaux de gris, cet argument correspond à une nuance de couleur à ignorer lors de l'application de l'algorithme d'égalisation d'histogramme. Si il n'est pas renseigné, toutes les nuances de couleurs sont prises en compte dans l'algorithme. 

equalizedImage : 
- Un objet de type `jimage` donc le champ `.image` est encodé en niveaux de gris
- Une matrice d'uint8 encodée en niveaux de gris

## Commentaire

J'attends vos commentaires concernant cette proposition de syntaxes. L'argument` transparencyColor` me parait poser problème car il représente ici deux choses : l'argument utilisé pour la conversion en niveaux de gris nécessaire dans le cas ou l'image en entrée est en couleurs et éventuellement une couleur à ignorer lors de l'application de l'algorithme...

**Comment by sgougeon** [comment]
À lire vos différents tickets, et en particulier celui-ci pour une fonction vraiment applicative, il devient évident que **jimstandard() doit devenir publique**.
En effet, avoir à ajouter toutes ces options pour chacune des fonctions "de traitement réel" du module n'est pas envisageable / souhaitable / ergonomique. Charge à l'utilisateur de standardiser explicitement l'entrée avant d'appeler la fonction visée. 
Cela ne doit pas empêcher d'appeler jimstandard() dans chaque fonction pour faire en sorte que l'entrée soit bien standard si elle ne l'est pas déjà, en utilisant les valeurs par défaut des paramètres de standardisation.

Je garde à l'esprit une question peu claire : pourquoi `colorsBits` ne peut-il pas être utile si `argb?=%t` ?
Par exemple, pourquoi avec "4444" le canal alpha entrant ne peut-il pas être encodé sur les 4 premiers bits de la matrice d'entrée ? Je n'ai pas vraiment compris votre réponse en lien avec Matplot_properties.

**Comment by Camtarrr** [comment]
C'est noté pour la fonction jimstandard(). Cela rendra plus compréhensible les syntaxes de nos fonctions. 

Je voulais juste dire que Matplot() ne prend pas en charge le cas "4444" où le canal alpha est encodé sur les 4 premiers bits. `gce().image_type` peut prendre la valeur "argb" ou la valeur "rgba444" mais pas les deux en même temps. En revanche cela ne nous empêche pas de gérer ce type de matrice d'entrée si il vous parait pertinent. Dans ce cas, il faudrait séparer l'argument `argb?` de `colorsBits` et `colormap`. Cela ne risque pas d'alourdir les syntaxes de jimstandard() ?

**Comment by sgougeon** [comment]
>Dans ce cas, il faudrait séparer l'argument argb? de colorsBits et colormap. Cela ne risque pas d'alourdir les syntaxes de jimstandard() ?

Je vous répondrai dans le ticket consacré à jimstandard()
Pour la page de _jimhistEqual_(), comme pour les pages des autres fonctions "applicatives" hors jimstandard() : la longue liste décrivant les formats et encodage d'images d'entrée doit clairement être plus concise et structurée. Proposition  : 

- **en couleurs**
  - hypermatrice RGB ou RGBA d'entiers int8 ou uint8, ou de décimaux sur [0, 1].
  - matrice 
    - d'entiers uint8 ou int8 sous découpage binaire "rgb332", ou décimaux équivalents sur [0, 255]
    - d'entiers uint16 ou int16 sous découpage binaire "rgba4444", ou décimaux équivalents sur [0, 2^16-1]
    - d'entiers uint32 ou int32 sous découpage binaire "rgba8888", ou décimaux équivalents sur [0, 2^32-1]
- **en niveaux de gris** :  matrice d'entiers uint8 ou int8, ou de décimaux sur [0, 1]
<note>Si l'image d'entrée a un autre encodage, on lui appliquera jimstandard() avant de la fournir à jimhistEqual().
</note>

**Question** :  en int8, int16 ou int32  : à quelle intensité correspond la valeur maximale (127 en int8) ?
**Remarque technique** : en XML docbook, **2^16** s'écrit `2<superscript>16</superscript>`.

Je vous laisse conclure et fermer ce ticket.

**Comment by Camtarrr** [comment]
127 en int8 correspond à 127 en uint8. Pour les nombres négatifs, -128 en int8 correspond à 128, -127 correspond à 129, etc. Cela fonctionne pareil pour les int16 et int32. 
Au départ, j'avais implémenté la conversion en pensant que 127 en int8 correspondait à 255 en uint8 mais l'image obtenue ne correspondait pas à l'image affichée par Matplot().

**Comment by Camtarrr** [comment]
- Dans le cas où l'image en entrée est une matrice d'entiers uint8 ou int8, l'encodage est considéré en niveau de gris par défaut. 
- Un objet `jimage` est accepté en entrée.

J'apporte juste ces deux modifications à votre proposition de liste de formats.

**Comment by sgougeon** [comment]
>- Dans le cas où l'image en entrée est une matrice d'entiers uint8 ou int8, l'encodage est considéré en niveau de gris par défaut.

oui, c'est déjà inclus dans la ligne
>SG: - **en niveaux de gris** :  matrice d'entiers uint8 ou int8, ou de décimaux sur [0, 1]

>CC: - Un objet `jimage` est accepté en entrée.

En effet, j'ai omis de compléter votre proposition initiale sur ce point.

**Comment by Camtarrr** [comment]
> - Dans le cas où l'image en entrée est une matrice d'entiers uint8 ou int8, l'encodage est considéré en niveau de gris par défaut.

J'aurais plutôt du dire : J'ai supprimé le cas 

> matrice
> - d'entiers uint8 ou int8 sous découpage binaire "rgb332", ou décimaux équivalents sur [0, 255]

car il est interprété par défaut comme une image en niveaux de gris. Il faudra donc utiliser jimstandard() au préalable si l'image est encodée en "rgb332".

**Comment by sgougeon** [comment]
Très juste. Je vous laisse ajuster dans le même sens la page de jimstandard() (ticket #24)
