### ISSUE TITLE
Utilisation de la fonction de création et d'édition d'objets jimage

### ISSUE THREAD

**Issue by JimSenee** [jimlab/jimlab#27]
La fonction de création ou d’édition d’un objet jimage a été créée.
Sa page d’aide est disponible en français à ce lien : [Page d'aide jimage() (français)](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimage.xml)

Avant toute chose, cette fonction s’appelle pour le moment `jimage2`. Sans le 2, chaque utilisation renvoie le warning `Attention : Redéfinition de la fonction : jimage`. Cela est peut-être dû à la présence de nombreuses variables appelées `jimage` au sein des fonctions du module ?

Elle permet de créer ou modifier un objet jimage à partir d’une (hyper)matrice ou d’un objet jimage, et d’arguments correspondant aux champs que nous avons définis.
Elle est fonctionnelle et la création se passe sans soucis. (Il manque pour le moment un élément important : la vérification de la compatibilité entre le champ `.encoding` renseigné et les dimensions de la  matrice d’entrée).

Toutefois, l’objectif de l’aspect « édition » de cette fonction me paraît moins clair pour le moment.
Un utilisateur ne doit a priori pas pouvoir modifier les champs `.encoding`, `.mime`, ou `.transparencyColor` à sa guise. (L’exemple dans le page d’aide n’a pas de sens actuellement)
L’intérêt réside-t-il seulement dans la modification du champ `.filename` ? Dans ce cas, les lignes 62-72 sont à revoir.
Comme nous avons pu l’évoquer, d’autres champs pourront être ajoutés dans un développement futur du module, et cette possibilité d’édition prendra peut-être un sens plus concret ?

L’utilisation de la fonction requiert la modification du nom du champ `.title` en `.format` dans la macro `%jimage_p`. Ce champ devra également être modifié dans toutes les fonctions l’utilisant, je m’en chargerai une fois que mes doutes concernant la fonction jimage() levés.

**Comment by sgougeon** [comment]
>Avant toute chose, cette fonction s’appelle pour le moment `jimage2`. Sans le 2, chaque utilisation renvoie le warning `Attention : Redéfinition de la fonction : jimage`. Cela est peut-être dû à la présence de nombreuses variables appelées `jimage` au sein des fonctions du module ?

En effet. Je vous invite à renommer toutes les variables `jimage` en `Jimage`.

Je réponds au reste dans un ou plusieurs messages à part.

**Comment by sgougeon** [comment]
>La fonction de création ou d’édition d’un objet jimage a été créée.
Sa page d’aide est disponible en français à ce lien : [Page d'aide jimage() (français)](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimage.xml)

Modifications proposées : 

- **Description courte** : Création d'un objet `jimage` à partir d'une matrice ou hypermatrice image.
  Remarque : on laisse de coté l'aspect modification. En effet, 
   - `.title` peut être modifié directement : image1.title = "Mon nouveau titre". Le fait de pouvoir éventuellement le déclarer dés la création est un service très pauvre. On peut s'en passer
   - `.mime` aussi : image1.mime = MIME;
     Cependant, il n'y aurait alors aucune vérification de la valeur du type MIME à affecter. Il est possible qu'à terme  nous supprimions ou déplacions ce champ "purement informationnel" (voir plus loin). Son utilité parait faible. Non ?
   - `.encoding` ne doit pas être modifié "à la main". Il faut passer par jimconvert() : c'est son rôle spécifique.

- **Liste d'arguments** : 
  - image : il faut pouvoir créer une jimage directement à partir de tous les types de matrices et hypermatrices interprétables par jimstandard().
Conséquences : 
    - toutes les options de jimstandard() doivent être disponibles en options de jimage() : 
        - colormap
        - argb?
        - colorsBits
      => les ajouter. transparencyColor est également non documentée.
     - encoding est donc inutile en argument. C'est une information issue du résultat de jimstandard() appelée par jimage().
  - Champ `.filename` ou champ plus générique `.infos` : ne pas s'en préoccuper.
    Comme `.title`, c'est un champ purement "pour information", qui n'a aucune incidence sur le traitement de l'image. Nous pourrions à terme regrouper ces champs informationnels dans une structure déclarée sous le champ primaire `.infos`. Nous aurons alors : `Jimage.infos.title`, `Jimage.infos.filename`, `Jimage.infos.mime`, etc.
Cela nécessiterait d'ajuster jimage_properties, %jimage_p, %jimage_disp, jimread, et jimwrite.

>L’utilisation de la fonction requiert la modification du nom du champ `.title` en `.format` dans la macro `%jimage_p`. Ce champ devra également être modifié dans toutes les fonctions l’utilisant, je m’en chargerai une fois que mes doutes concernant la fonction jimage() levés.

Les fonctionnalités vous paraissent-elles plus claires maintenant ?

**Comment by sgougeon** [comment]
>>GS: Avant toute chose, cette fonction s’appelle pour le moment `jimage2`. Sans le 2, chaque utilisation renvoie le warning `Attention : Redéfinition de la fonction : jimage`. Cela est peut-être dû à la présence de nombreuses variables appelées `jimage` au sein des fonctions du module ?
>
>SG: En effet. Je vous invite à renommer toutes les variables `jimage` en `Jimage`.

C'est maintenant fait. En outre, jimage2() est maintenant renommée jimage(). Vous pouvez donc désormais l'utiliser dans le code sans risque de conflits.

**Comment by JimSenee** [comment]
Vous m'avez devancé sur ce point, je vous en remercie.
Les autres modifications de la fonction sont en cours de réalisation.

**Comment by JimSenee** [comment]
Les modifications ont été effectuées.
Quelques observations avec du recul (pour être certain que nous allions dans le même sens) :

• Les champs `.mime` et `.title` sont mis à leur valeur par défaut : ‘user’ et ‘unknown’. Ils n’ont pas vocation à être modifiés par `jimage()` et sont purement informatifs.
Ils pourront par la suite être modifiés par l’utilisateur via la console simplement, et pourquoi pas regroupés sous un champ `.infos`.

> toutes les options de jimstandard() doivent être disponibles en options de jimage() :
> • colormap
> • argb?
> • colorsBits
> => les ajouter.

• C'est maintenant le cas.

 > transparencyColor est également non documentée.

• Le champ `.transparencyColor` est pour le moment mis par défaut à -1.
Je ne comprend pas bien ce que vous voulez dire concernant ce champ. Doit-il aussi être modifiable via un argument d’entrée de la fonction ?

• Le champ `.encoding` est actualisé suite à l’appel de `jimstandard()` : un test du nombre de couches de la matrice détermine son encodage : ‘gray’ pour 1, ‘rgb’ pour 3 et ‘rgba’ pour 4.

• L’argument de sortie originalType de jimstandard() est ici perdu. Peut-être pourrait-il être ajouté dans le futur champ `.infos` ?

**Comment by sgougeon** [comment]
Je réponds au détail : 
>• Les champs .mime et .title sont mis à leur valeur par défaut : ‘user’ et ‘unknown’. 

Il faut être le plus sobre possible : "" et "" convient mieux.

>Ils n’ont pas vocation à être modifiés par jimage() et sont purement informatifs.

Outre la création de la mlist r = mlist(["jimage" "image"], jimstandard(image)),  renseigner ces champs à la création de la jimage est pourtant quasiment le seul intérêt de jimage() par rapport à jimstandard()...
Pour le moment, vu en effet le faible intérêt de ces champs, restons-en là.

>Ils pourront par la suite être modifiés par l’utilisateur via la console simplement, et pourquoi pas regroupés sous un champ .infos.
>• Le champ .transparencyColor est pour le moment mis par défaut à -1.
>Je ne comprend pas bien ce que vous voulez dire concernant ce champ. Doit-il aussi être modifiable via un argument d’entrée de la fonction ?

Oui. C'est probablement le champ le plus utile.
Il est facile d'analyser ces saisies stockées dans varargin : elles vont par paires : le nom du champ, suivi de sa valeur : nom1,val1, nom2,val2, etc.

>• Le champ .encoding est actualisé suite à l’appel de jimstandard() : un test du nombre de couches de la matrice détermine son encodage : ‘gray’ pour 1, ‘rgb’ pour 3 et ‘rgba’ pour 4.

Ce champ est voué à disparaitre. Il ne peut pas faire foi devant le nombre de couches, et pose inutilement des problèmes de synchronisation (comme à chaque fois qu'une info est redondante). Il sera remplacé par une fonction `jimtype()`. Avant cela, il reste cependant des aspects à résoudre, notamment concernant la prise en charge des matrices booléennes et un éventuel typage jimage correspondant.

>• L’argument de sortie originalType de jimstandard() est ici perdu. Peut-être pourrait-il être ajouté dans le futur champ .infos ?

Je n'en vois pas l'intérêt à priori.

Merci pour le travail effectué.
Je vous laisse le soin de fermer le ticket lorsqu'approprié.

**Comment by JimSenee** [comment]
Changements effectués.
Le champ `.encoding` n'est pas modifiable par l'utilisateur. Il teste toujours le nombre de couches, ce qui sera à adapter après l'ajout potentiel de `jimtype()`.
