### ISSUE TITLE
Erreur dans les tests avec la fonction Matplot()

### ISSUE THREAD

**Issue by JimSenee** [jimlab/jimlab#3]
DESCRIPTION DE L'ERREUR :
-----------------------------

Version Scilab : 5.5.2
Le fichier de test de `jimdisp()` renvoie False. Pourtant, les lignes une à une fonctionnent. Comme indiqué par Scilab, j'ai lancé la commande `exec("H:\PROJETS\4A\jimlab\jimlab-master\tests\unit_tests\jimdisp.tst");` et tout fonctionne bien.

LOG DE L'ERREUR :
--------------------
```
-->   lasterror()
 ans  =
 
 Le parent doit être une sous-fenêtre   
```

COMMENT REPRODUIRE L'ERREUR :
--------------------------------------

Exécuter les tests joints au ticket, dans le dossier compressé.

INFORMATIONS SUPPLÉMENTAIRES :
--------------------------------------

En regardant les rapports jimdisp.dia.tmp et jimdisp.res, l'erreur affichée est "Le parent doit être une sous fenêtre" que je ne comprend pas.
J'ai testé avec la fonction `Matplot()` uniquement, ce qui renvoie la même erreur. Cela ne semble donc pas venir de `jimdisp()`.

**Comment by sgougeon** [comment]
Le fait que l'exec() direct se passe bien nous suffit pour le moment. 
Sans succès pour le moment, je continue à rechercher l'origine de ce problème.
Je remarque que le rapport d'erreur donné par test_run() est peu informatif. En particulier, la ligne du test à laquelle le problème apparait n'est pas indiquée. C'est assurément une insuffisance de test_run() en 5.5.2. test_run() a beaucoup été améliorée dans Scilab 6.0 : le rapport d'erreur du test est beaucoup plus explicite. 
Je vous propose de poursuivre le traitement de ce bug de mon coté.
Si des modifications de fonctions jimlab sont nécessaires pour le résoudre, je posterais des tickets à l'adresse des auteurs concerné-e-s.

**Comment by sgougeon** [comment]
>J'ai testé avec la fonction Matplot() uniquement, ce qui renvoie la même erreur.
En effet : en Scilab 6, "test_run graphics Matplot show_error" échoue avec une erreur à explorer.
Plusieurs rapport de bugs ont déjà été postés sur Bugzilla concernant Matplot : voir par exemple
uman Matplot|Matplot1 wb
et http://mailinglists.scilab.org/Scilab-users-Native-managed-Hypermatrices-affect-the-Matplot-functionality-td4035788.html
Solutions intégrées ce matin : 
https://codereview.scilab.org/19178
https://codereview.scilab.org/19179
Problème restant : http://bugzilla.scilab.org/14884
Je regarderai en fin de semaine avec le master de Scilab si les solutions intégrées ce matin résolvent notre problème.

**Comment by sgougeon** [comment]
Le master de la branche 6.0 daté du 22/3 à 6h36 et intégrant les 2 correctifs de Matplot évoqués antérieurement est installé sur le H:\ et peut être lancé avec le raccourci "H:\DISTRI_DOC_ETU\APPLI_RESEAU\Scilab\Scilab 6.0.0 master"
Avec cette version, les instructions suivantes donnent une erreur, mais différente de la précédente :
```
cd("H:\PROJETS\4A\jimlab\jimlab-master");
exec("loader.sce", -1);
test_run(".","jimdisp","show_error")
```

```
-------------- RESULTAT --------------
--> test_run(".","jimdisp","show_error")
   TMPDIR = D:\Users\sgougeon\AppData\Local\Temp\SCI_TMP_2692_11638

   001/001 - [.] jimdisp........................................failed: Slave Scilab exited with error code 1 

   --------------------------------------------------------------------------
   Summary

   tests              1 - 100 %
   passed             0 -   0 %
   failed             1 - 100 %
   skipped            0
   length             23.82 sec
   --------------------------------------------------------------------------
   Details

   TEST : [.] jimdisp
   failed: Slave Scilab exited with error code 1
   
   ----- TMPDIR\jimdisp.res: 10 last lines: -----
   --> //imagePath = getlongpathname(mp +'tests\images\noError\rgb.jpg');
   --> //disp(imagePath);
   --> imagePath = jimlabPath +'\tests\images\noError\rgb.jpg';
   --> jimage1 = jimread(imagePath);
   --> jimdisp(jimage1);
   à la ligne     4 de la fonction %h_e     ( H:\DQ9SIE~W\AWZYEX~7\Scilab\SPDUQW~8\modules\graphics\macros\%h_e.sci ligne 16 )
   dans la fonction native        jimreset ( H:\PROJETS\4A\jimlab\JCAGWG~B\macros\jimdisp.sci ligne 120 )
   à la ligne    25 de la fonction jimdisp  ( H:\PROJETS\4A\jimlab\JCAGWG~B\macros\jimdisp.sci ligne 33 )
   à la ligne    36 du fichier exécuté TMPDIR\jimdisp.tst
   get : Le handle n'est pas ou n'est plus valide.
   --------------------------------------------------------------------------
 ans  =
  F
```
L'exécution directe du test donne maintenant aussi une erreur :
> --> exec('H:\PROJETS\4A\jimlab\jimlab-master\tests\unit_tests\jimdisp.tst', -1)
> dans la fonction native        jimdisp ( H:\PROJETS\4A\jimlab\JCAGWG~B\macros\jimdisp.sci ligne 8 )
> à la ligne    20 du fichier exécuté H:\PROJETS\4A\jimlab\jimlab-master\tests\unit_tests\jimdisp.tst
> 
> Opération indéfinie pour les opérandes données.
> vérifier ou définir la fonction %_o_c pour la surcharge.

Je vous redonne la main sur ce ticket pour explorer ces 2 erreurs.
La version de jimdisp() compilée et exécutée est celle disponible sur Github ce soir.

**Comment by JimSenee** [comment]
L'erreur vient effectivement de l'appel du handle dans la sous-fonction jimreset().
Cet appel sert à réinitialiser la chaîne de caractères "ax.title.text". Cela peut être fait lors de l'appel de la sous-fonction jimdisp_mat(), ce qui permet de ne pas rappeler le handle dans jimreset(), et l'erreur de non validité du handle disparaît, tout en arrivant au résultat escompté.

Cependant, une erreur différente est renvoyée :

```
cd("H:\PROJETS\4A\jimlab\jimlab-master");
exec("loader.sce", -1);
test_run(".","jimdisp","show_error")
```

```
TMPDIR = D:\Users\e154644\AppData\Local\Temp\SCI_TMP_6172_11169

   001/001 - [.] jimdisp........................................failed: Slave Scilab exited with error code 1 

   --------------------------------------------------------------------------
   Summary

   tests              1 - 100 %
   passed             0 -   0 %
   failed             1 - 100 %
   skipped            0
   length             20.01 sec
   --------------------------------------------------------------------------
   Details



   TEST : [.] jimdisp
   failed: Slave Scilab exited with error code 1
   
   ----- TMPDIR\jimdisp.res: 10 last lines: -----
   --> //[m, mp] = libraryinfo('jimlablib');
   --> //imagePath = getlongpathname(mp +'tests\images\noError\rgb.jpg');
   --> //disp(imagePath);
   --> imagePath = jimlabPath +'\tests\images\noError\rgb.jpg';
   --> jimage1 = jimread(imagePath);
   --> jimdisp(jimage1);
   à la ligne    17 de la fonction jimdisp_mat ( H:\PROJETS\4A\jimlab\JCAGWG~B\macros\jimdisp.sci ligne 63 )
   à la ligne    26 de la fonction jimdisp     ( H:\PROJETS\4A\jimlab\JCAGWG~B\macros\jimdisp.sci ligne 34 )
   à la ligne    36 du fichier exécuté TMPDIR\jimdisp.tst
   grayplot : Plus de mémoire disponible.


   --------------------------------------------------------------------------
 ans  =

  F
```

Concernant l'erreur lors de l'éxecution du test direct, elle vient du passage de la fonction exists() à la fonction isdef() dans le code de jimdisp(). Elle a été résolue en modifiant les tests initiaux :
```
if ~isdef('info','l') | type(info) == 0  then
    info = 'no';
end
if ~isdef('box','l') | type(box) == 0 then
    box = 'no';
end
```

**Comment by sgougeon** [comment]
Le problème de mémoire insuffisante pour grayplot() a fait l'objet du rapport de bug 
http://bugzilla.scilab.org/8747 dés 2011, et n'a toujours pas été résolu.
Je vais essayer de réactiver la résolution de ce problème au niveau central.

**Comment by JimSenee** [comment]
Le test fonctionne sous MacOS sur les deux versions de Scilab.
L'erreur venant de `grayplot()` n'était plus indiquée, mais l'appel de l'URL par `jimread()` posait problème en 5.5.2. L'appel de l'URL fonctionnait bien sur 6.0.
J'ai donc rajouté un test de version et d'OS dans le test, pour cibler la condition [MacOS + Scilab 5.5.2] et éviter cet appel. Est-ce une solution viable ?

Le test est disponible ici : [jimdisp.tst](https://github.com/jimlab/jimlab/blob/master/tests/unit_tests/jimdisp.tst)

```
--> test_run(jimlabPath(),'jimdisp','no_check_error_output')
   TMPDIR = /private/var/folders/wz/jgr3t_ds1hq5wm37wk4p5ldh0000gn/T/SCI_TMP_8502_0cBoqu

   001/001 - [/Users/Gael/Desktop/ENSIM/JIMLAB/0306/5.5.2] jimdisp passed

   --------------------------------------------------------------------------
   Summary

   tests              1 - 100 %
   passed             1 - 100 %
   failed             0 -   0 %
   skipped            0
   length             10.20 sec
   --------------------------------------------------------------------------
 ans  =
 
  T  
```

```
--> test_run(jimlabPath(),'jimdisp')
   TMPDIR = /var/folders/wz/jgr3t_ds1hq5wm37wk4p5ldh0000gn/T//SCI_TMP_8028_xmkHiQ

   001/001 - [/Users/Gael/Desktop/ENSIM/JIMLAB/0306/6.0] jimdisp passed

   --------------------------------------------------------------------------
   Summary

   tests              1 - 100 %
   passed             1 - 100 %
   failed             0 -   0 %
   skipped            0
   length             15.36 sec
   --------------------------------------------------------------------------
 ans  =

  T

```

Je ne comprend toutefois pas pourquoi le problème de mémoire de `grayplot()` n'apparaît plus.

**Comment by sgougeon** [comment]
Pour l'URL : 
-  Essayer avec une image sur une URL non sécurisée (http://)
- Si toujours requis : refuser sur les 3 versions 5.5.x : msprintf("%d.%d",getversion("scilab"))=="5.5".
  appeler getos()

Pour grayplot qui passe : je ne sais pas. Sous windows, l'erreur se produit encore :(

**Comment by JimSenee** [comment]
L'erreur n'apparaît plus sur nos machines en 5.5.2 et 6.0 (vérifié sous MacOS et Windows), le test de version et d'OS a donc été retiré. De plus l'URL a été changé vers un URL non sécurisé.
