### ISSUE TITLE
edit_curv() : coordonnées négatives

### ISSUE THREAD

**Issue by JimSenee** [jimlab/jimlab#33]
La version étendue d'edit_curv() est bien fonctionnelle.
J'ai cependant remarqué un détail qui devrait être corrigé : il est possible de sélectionner un point de coordonnées négatives, ce qui n'est pas opportun pour l'utilisation que l'on souhaite en faire.

**Comment by sgougeon** [comment]
Il n'est désormais plus possible de créer un point hors du cadre du repère graphique.
Par ailleurs, une pression sur DEL sans sélection préalable d'un point ne crée plus de point.
