### ISSUE TITLE
Illustation de l'utilisation de l'argument transparencyColor dans le fonction jimhistEqual()

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#34]
L'image ci-dessous montre : 

- en haut à gauche, l'image originale `Image`,
- en haut à droite, l'image après égalisation d'histogramme sans avoir renseigné l'argument `transparencyColor` obtenue par la syntaxe `equalizedImage = jimhistEqual(Image)`,
- en bas à gauche, l'image après égalisation d'histogramme en ayant renseigné le blanc comme couleur de transparence : `equalizedImage = jimhistEqual(Image, 255)`.

![exemple](https://cloud.githubusercontent.com/assets/24584359/26688698/b19a31a0-46f3-11e7-9d2b-41765e547893.png)

En fait, l'argument `transparencyColor` permet d'améliorer le contraste entre les pixels non transparents d'une image. Il est inutile de le renseigner si l'objectif est (comme dans le cas du logo) de faire ressortir les pixels non transparents par rapport au fond. 
J'espère avoir été plus claire. Si ce n'est pas le cas, j'attends vos questions. 

Si l'utilisation de la couleur de transparence n'est pas celle que vous attendiez, elle peut être modifiée.

**Comment by sgougeon** [comment]
Je comprends mieux : vous excluez la couleur de transparence car vous l'assimilez à la couleur de fond (ce qui est raisonnable) et vous supposez qu'une fraction importante des pixels sont concernés. En la traitant sans égard particulier, l'égalisation vide  / empêche le peuplement des niveaux d'intensité d'un large voisinage du niveau transparent (translaté), ce qui peut confiner les autres niveaux à une plage étroite résultant en une faible efficacité de la fonction. 
J'ai consulté la macro : la couleur de transparence est inchangée (on pourrait en discuter, mais OK), et les niveaux translatés ne viennent pas la collisionner (ce qui est impératif : OK).

La page d'aide mériterait quelques précisions concernant la couleur de transparence : 

1. Vous avez écrit : _Dans le cas où le champ .transparencyColor est différent de -1, la couleur de transparence n'est pas prise en compte dans l'algorithme d'égalisation d'histogramme_
Cela semble erroné : elle l'est, si l'option n'est pas fournie.
2. Indiquer que la fonction ne modifie pas la couleur de transparence ni les pixels ayant cette couleur.
3. Le cas où on passe une jimage ayant une .transparencyColor active ET une TC de consigne en option n'est pas clairement évoqué. Sauf erreur, le code remplace la valeur du champ par la valeur consignée en option. Je ne pense pas que ce forçage soit souhaitable. Si l'utilisateur veut changer la valeur de la TC, il peut/doit à mon sens le faire **avant** l'appel à jimhistEqual() :  
```
Jimage.transparencyColor = ma_valeur; 
jimhistEqual(Jimage);  // l'option n'est alors plus utile
```
Du coup, lorsqu'on passe une TC en option, la .TC est traitée comme les autres et est donc translatée. Si sa valeur n'est plus écrasée par celle de l'option, il faudra l'actualiser avec la valeur translatée.

En pratique, tout cela me semble assez compliqué, pas très lisible. La TC en option est pratique si on passe une image. Elle prête à confusion si on passe une jimage. On pourrait donc penser à une option plus générique : 
```
            equalizediImage = jimhistEqual(image)
            [equalizedImage, newTC] = jimhistEqual(image, ignoredTC)
```
avec
```
ignoredTC :
- si image est une jimage : booléen, %T (par défaut) si les pixels transparents ne doivent pas 
  être comptés, %F sinon.
- si image est une matrice ou hypermatrice : scalaire _Gray_ ou vecteur ou hypermatrice _[r g b]_ : 
  intensité ou couleur des pixels considérés comme transparents et à ne pas compter.
```
Dans les deux cas, l'algorithme mériterait d'être simplifié, sans perdre en efficacité : 

- On calcule l'histogramme complet
- Si les pixels transparents ne doivent pas être comptés : on force et réduit la population du canal transparent à 1 (niveau minimum non nul)(seulement dans l'histogramme). On peut aussi préférer une autre valeur telle que la population moyenne, ou le min() entre la hauteur réelle du canal et la population moyenne.
- On calcule les nouvelles intensités des canaux. On actualise l'image, y compris les pixels transparents.
- On actualise Jimage.transparencyColor ou on retourne newTC

Un avantage important de cet algorithme est qu'il ne modifie pas l'_interclassement_ de la couleur de transparence. Appliqué à votre exemple illustré ci-dessus, il donnerait un résultat identique.

Cela représente des modifications non négligeables. À l'issue de votre projet, je prévois d'étendre la fonction a) pour pouvoir équilibrer les images couleurs  b) pour pouvoir étendre l'histogramme sur un domaine au choix plus restreint que [0 255] (pour une raison que nous pourrons évoquer) en utilisant une nouvelle option. 
Je vous propose de garder jimhistEqual() en l'état pour le moment, afin de ne pas reprendre la macro, les pages, et les tests à 2 reprises. Vous pouvez juste traiter les points 1 et 2 concernant la page d'aide, avant de fermer le ticket.

NB: en RGBA en entrée, il faudra aussi réfléchir à la prise en compte ou non des pixels à A=0

**Comment by Camtarrr** [comment]
C'est noté ! La page d'aide va être modifiée rapidement. 
En ce qui concerne les points suivants, je les traiterais après l'issue du projet si cela vous convient.

**Comment by Camtarrr** [comment]
Les pages d'aides en anglais et en français ont été modifiées.
