### ISSUE TITLE
Relecture de la page d'aide de jimroi()

### ISSUE THREAD

**Issue by JimSenee** [jimlab/jimlab#35]
La page d'aide de jimroi() a été finalisée et actualisée suite aux derniers changements de la fonction.
Elle est disponible en français à ce lien : [Page d'aide jimroi() (FR)](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimroi.xml)

En attente d'une relecture avant de finaliser la traduction en anglais.

**Comment by sgougeon** [comment]
Merci. Voici ci-joint mes nouvelles remarques. Il est nécessaire de simplifier les syntaxes.
Si, dans le code, l'analyse des arguments d'entrée pose une difficulté, n'hésitez pas à revenir vers moi.

[jimroi_Help_170605.pdf](https://github.com/jimlab/jimlab/files/1052967/jimroi_Help_170605.pdf)

**Comment by JimSenee** [comment]
(GitHub a été plus rapide que moi visiblement !)

J'ai tenu compte des remarques et ai mis à jour la page d'aide. La fonction a alors dû être modifiée pour suivre cette mise à jour.

Si la page d'aide est maintenant correcte, je fermerai le ticket et finirai sa traduction en anglais.

**Comment by JimSenee** [comment]
Pages d'aide en français et anglais mises à jour.
