### ISSUE TITLE
jimdisp() : par défaut, une matrice simple doit être interprétée et affichée en niveaux de gris

### ISSUE THREAD

**Issue by sgougeon** [jimlab/jimlab#37]
Actuellement, jimdisp() recevant une matrice simple de décimaux entre 0 et 255 les utilise comme s'il s'agissait de numéros de couleurs. Cela ne convient pas : par défaut, une matrice de décimaux sur [0 1] ou d'entiers ou de décimaux sur [0 255] doit être interprétée comme des niveaux de gris.
Pour interpréter une telle entrée en numéros de couleurs, une option "cm" ou "colormap" (on peut accepter les 2 de manière équivalente) peut être proposée.
```
m = grand(100,100,"uin",0,255);
scf();
subplot(1,2,1), jimdisp(m)
subplot(1,2,2), jimdisp(jiminvert(m))
```
![image](https://cloud.githubusercontent.com/assets/5930727/26832083/927ff7da-4ace-11e7-95e1-ab2aff37dd13.png)

**Comment by JimSenee** [comment]
`jimstandard()` n'est actuellement pas appelée par `jimdisp()`. On remarque bien la bonne interprétation après le passage par `jiminvert()` (qui appelle `jimstandard() `en interne).
Doit on alors simplement rajouter l'appel de `jimstandard() `dans le cas où l'image en entrée n'est pas un objet jimage, ou souhaitez-vous tout de même ajouter l'argument donnant le colormap ?

**Comment by sgougeon** [comment]
>jimstandard() n'est actuellement pas appelée par jimdisp().

Il faut en premier lieu y remédier.
Puis il faut juste pouvoir dire à jimdisp() d'utiliser la colormap courante de la fenêtre cible.
Prévoir le passage d'une colormap alternative sera peu utile. Ca peut être fait en une demi-ligne `gcf().color_map = ..` avant ou après l'affichage, dans les cas rares où ce serait utile.

**Comment by JimSenee** [comment]
L’appel à `jimstandard()` a été ajouté et l’affichage se fait correctement.
Cependant je ne comprend toujours pas cette histoire de colormap.

> Puis il faut juste pouvoir dire à jimdisp() d'utiliser la colormap courante de la fenêtre cible.
La colormap de la fenêtre cible n’est pas celle que l’on veut : par défaut il s’agit d’une colormap de 32 couleurs, d’où le premier affichage faussé.

On peut obtenir le bon affichage en la changeant via la commande :
```
f = gcf() ;
f.color_map = graycolormap(255) ;
```

Cela pourrait apparaître dans les lignes de code de `jimdisp()` si la matrice en entrée est detectée comme une matrice à une seule couche (en niveaux de gris), et cela résoudrait bien le problème. Mais ce n’est pas du tout l’objectif comme vous l’avez précisé juste ensuite.
Je ne vois donc vraiment pas du tout où vous voulez en venir avec l’expression « utiliser la colormap courante de la fenêtre cible».
Il sera peut être plus simple d’en parler de vive voix mardi.

**Comment by JimSenee** [comment]
Après clarification aujourd'hui, les modifications sont faites. Cela sera à adapter dans votre version du 0.2 qui sera postée d'ici peu.
