### ISSUE TITLE
Matrice d'entiers non supportée par la fonction jiminvert()

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#4]
DESCRIPTION DE L'ERREUR :
-----------------------------

Version Scilab : 5.5.2
La fonction jiminvert() n'accepte pas ma matrice codée en uint8. 

LOG DE L'ERREUR :
--------------------
```
 !--error 10000 
Not any jimage or matrix argument have been definded
at line      16 of function jiminvert called by :  
inv = jiminvert(mat)

```

COMMENT REPRODUIRE L'ERREUR :
--------------------------------------
`chdir('H:\PROJETS\4A\jimlab\jimlab-master')`
`exec('builder.sce')`
`exec('loader.sce')`
`mat = uint8([155 155; 255 255]);`
`inv = jiminvert(mat)`

**Comment by sgougeon** [comment]
Je n'obtiens pas le même message d'erreur : 
```
-->exec(get_absolute_file_path("loader.sce")+"etc\"+"jimlab.start");
Start jimlab
	Load macros
	Load help
-->mat = uint8([155 155; 255 255]);
-->inv = jiminvert(mat)
        !--error 999 
Overloaded load cannot occur in this context 

```

**Comment by sgougeon** [comment]
OK : après mise à jour sur le H:\ avec la dernière version du .sci, je reproduis bien l'erreur indiquée.

**Comment by sgougeon** [comment]
L'origine de cette erreur est évoquée dans une des remarques du PDF commenté joint.
SVP traiter ces différentes remarques.
[jiminvert.sci_1703162000.pdf](https://github.com/jimlab/jimlab/files/848880/jiminvert.sci_1703162000.pdf)

**Comment by nicojim** [comment]
La plupart des remarques ont été traitées. Je propose de discuter jeudi 23/04 en équipe le développement de la fonction de conversion des différents types vers un objet jimage puisque qu'elle concerne plusieurs fonction.

**Comment by sgougeon** [comment]
Si ce ticket est résolu, merci de bien vouloir le fermer. Sinon SVP l'actualiser.

**Comment by sgougeon** [comment]
La remarque figurant en ligne 22 dans le dernier PDF commenté posté n'a pas été traitée.
jiminvert() ne peut donc toujours pas traiter les matrices "simples", contrairement à ce que prétend sa page d'aide (et le cahier des charges).

**Comment by nicojim** [comment]
Traité grâce à jimstandard

**Comment by Camtarrr** [comment]
Jimstandard() ne résout pas le problème du type en sortie, si ? 
Avec gaël, on pensait créer un fonction faisant la conversion inverse.

**Comment by nicojim** [comment]
Oui =, j'avais mal relus le problème du ticket

**Comment by sgougeon** [comment]
>CC: Jimstandard() ne résout pas le problème du type en sortie, si ?
>Avec gaël, on pensait créer un fonction faisant la conversion inverse.

Pouvez-vous préciser de quel problème il s'agit ? S'il n'est pas propre à jiminvert(), préférer l'ouverture d'un nouveau ticket.

**Comment by Camtarrr** [comment]
> SG : La remarque figurant en ligne 22 dans le dernier PDF commenté posté n'a pas été traitée.
> jiminvert() ne peut donc toujours pas traiter les matrices "simples", contrairement à ce que prétend sa page d'aide (et le cahier des charges).

La dernière partie de cette remarque n'est toujours pas traitée.

**Comment by sgougeon** [comment]
>La dernière partie de cette remarque n'est toujours pas traitée.

?
Le code sur Git est OK : la condition >= est OK, et invert travaille comme attendu :
`    elseif((typeof(image) == "hypermat")|(ndims(image) >= 2)) // Testing aruments's type`

**Comment by Camtarrr** [comment]
Le type de l'image en sortie est toujours uint8, il ne correspond pas au type de l'image d'entrée.

**Comment by sgougeon** [comment]
En quoi est-ce gênant ?

**Comment by Camtarrr** [comment]
Selon votre commentaire en ligne 22 de votre correction d'un ancien commit de jiminvert() [jiminvert.sci_1703162000.pdf](https://github.com/jimlab/jimlab/files/848880/jiminvert.sci_1703162000.pdf) :
> [...] le résultat de jiminvert() devant être du même type que ce que l'on a fourni.

Si ce n'est plus un problème, le ticket peut être fermé.
