### ISSUE TITLE
démarche jimbur;

### ISSUE THREAD

**Issue by JimAmel** [jimlab/jimlab#5]
//Copyright (C) 2017 - ENSIM, Université du Maine - Alix Melaine Mnoubue
//This file must be used under the terms of the CeCILL.
//This source file is licensed as described in the file COPYING, which
//you should have received as part of this distribution.  The terms
//are also available at    
//http://www.cecill.info/licences/Licence_CeCILL_V2.1-fr.txt

function [IMB]=testblur(M,sigma,rayon)

if(typeof(M) == 'hypermat') // Testing aruments's type
        arg_jimage = 0;
        im_mod = M;
    elseif(typeof(M) == "jimage")
        arg_jimage = 1;
        
        im = M.image;
    else
        error('Not any jimage or matrix argument have been definded')     
    end
  
   select argn(2)
            case 1 then
               sigma = 5;
            case 0 then
               error('Invalid number of arguments.');
           end
           
           if(sigma==1) then   error('erreur');end
           if(rayon<1) then   error('erreur');end
    Kf=0;
    hw = jcompile("Kernel", ["public class Kernel {"
                             "public static double [] createKernel(double sigma,int kernelsize) {"
                            " double[] kernel = new double[kernelsize*kernelsize];"
	"for(int i = 0;  i < kernelsize; i++){"
			"double x = i - (kernelsize -1) / 2;"
			"for(int j = 0; j < kernelsize; j++){"
				"double y = j - (kernelsize -1)/2;"
				"kernel[j + i*kernelsize] = 1 / (2 * Math.PI * sigma * sigma) * Math.exp(-(x*x + y*y) / (2 * sigma *sigma));"
			"}"
		"}"
		"float sum = 0;"
	"for(int i = 0; i < kernelsize; i++){"	
		"for(int j = 0; j < kernelsize; j++){"
			"sum += kernel[j + i*kernelsize];"
			"}"
				"}"
			
		"for(int i = 0; i < kernelsize; i++){"
		"for(int j = 0; j < kernelsize; j++){"
               "kernel[j + i*kernelsize] /= sum;"
			"}"
				"}"
    "return kernel;"   
                        "}"
                             "}"]);

               
     
    
 Kernel= hw.createKernel(sigma,rayon);     
 
        K = Kernel;
        
        typeof(K)
        typeof(jwrap(K))

        IMB= convol2d(K,double(im));   
      
        
endfunction

**Comment by sgougeon** [comment]
Ce code a été commenté et les questions associées ont été discutées ce jeudi en réunion de travail
