### ISSUE TITLE
Test des variables d'entrés de jimwrite

### ISSUE THREAD

**Issue by nicojim** [jimlab/jimlab#6]
Bonjour, je souhaiterais avoir vos remarques concernant les tests effectués sur les variables d'entrés de jimwrite. Est-il judicieux d'affecter des valeurs par défaut aux variable en cas de mauvaise saisie?

**Comment by nicojim** [comment]
Cas du chemin du répertoire d'entré : 

> `function jimwrite( jimage, imageMat, imagePath, typeMIME, Name, Encoding)
> 
> if(~isdef(["imagePath"],"l") | type(imagePath) ~= 10) //Verify if imagePath is a string  
>         warning('Invalid Path of file, the current depository will be used');
>         imagePath = pwd;
> end`

**Comment by nicojim** [comment]
Cas du type MIME

`function jimwrite( jimage, imageMat, imagePath, typeMIME, Name, Encoding)`

 

```

>  if(isdef(["typeMIME"],"l"))
> 
>          invalid_typeMIME = 0;
>          deftypeMIME = ['jpg','png','gif','bmp'];
>          comptypeMIME = strstr(deftypeMIME,typeMIME); // Verify if user's specified format is supported
>            if((type(typeMIME) ~= 10)|(comptypeMIME == '')) // If typeMIME is not definded or wrong, 
>                 invalid_typeMIME = 1;
>            end
>       elseif(~(isdef(["typeMIME"],"l"))) 
>           
>           invalid_typeMIME = 1;
>       end
>       
>       if(arg_jimage & invalid_typeMIME) // Jimage typeMIME is used 
>           typeMIME = part(jimage.format,[2:length(jimage.format)])
>            warning('Invalid typeMIME detected, jimage typeMIME will be used :'..
>           + typeMIME)
>      elseif(invalid_typeMIME)
>           typeMIME = 'jpg';
>           warning('Undefineded typeMIME, jpg will be used')
> end

```

**Comment by sgougeon** [comment]
J'ai en premier lieu lu et commenté la page d'aide de jimwrite(), version la plus récente sur GitHub.
Le PDF commenté est joint. N'hésitez pas à me contacter ou si besoin venir me voir pour y retravailler.
[jimwrite_170406.1040_REM.pdf](https://github.com/jimlab/jimlab/files/902247/jimwrite_170406.1040_REM.pdf)
