### ISSUE TITLE
age d'aide française de jimwrite terminée

### ISSUE THREAD

**Issue by nicojim** [jimlab/jimlab#7]
La page d'aide de jimwrite est rédigé en français. Pouvez vous me donner vos remarques avant la traduction?

[Page d'aide de jimwrite](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimwrite.xml)

**Comment by sgougeon** [comment]
La page est complètement commentée ici : 
https://github.com/jimlab/jimlab/issues/6/#issuecomment-292133044
Le code nécessite d'être retravaillé pour traiter notamment la question des arguments d'entrée faisant l'objet du ticket #6. La page d'aide en sera donc modifiée.
Pour la partie Description : éviter de répéter ce qui est écrit de manière plus ciblée dans la description des Arguments. Je prèfère vous inviter à ajouter des choses manquantes que vous inviter à supprimer des choses redondantes (à la rédaction desquelles vous aurez investi du temps).

**Comment by nicojim** [comment]
Page terminé
