### ISSUE TITLE
Page d'aide en français de jimread() terminée

### ISSUE THREAD

**Issue by Camtarrr** [jimlab/jimlab#8]
La rédaction de la page d'aide de la fonction jimread() en français est terminée.
Pouvez vous m'indiquer les points à changer avant la traduction en anglais ?

[Page d'aide de jimread()](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimread.xml)

**Comment by sgougeon** [comment]
Mes remarques concernant les contenus sont jointes sur le PDF issu de la sortie HTML.
La partie technique XML est correcte.
[jimread_170323_REMS.pdf](https://github.com/jimlab/jimlab/files/865492/jimread_170323_REMS.pdf)

**Comment by Camtarrr** [comment]
J'ai actualisé la page d'aide de la fonction jimread() en prenant en compte vos commentaires. Serait-il possible d'avoir la validation pour commencer la traduction ou des nouveaux commentaires si il y a des points à améliorer ? 

[Page d'aide actualisée](https://github.com/jimlab/jimlab/blob/master/help/fr_FR/jimread.xml)

**Comment by sgougeon** [comment]
La version française est relue ci-après. Vous pourrez entreprendre la traduction en anglais directement après la prise en compte des dernières remarques, sans re-soumission ici.
[jimread_help_20170416_REM.pdf](https://github.com/jimlab/jimlab/files/928540/jimread_help_20170416_REM.pdf)
